name: BuildAndPushImageOnHarborAndUpdateArgoCDConfig

on:
  push:
    branches: [ "main" ]
env:
  REGISTRY: harbor.mongodb.dk
 
jobs:
   
  harbor:    
    uses: KarsoeTools/actionTemplates/.github/workflows/angular.yaml@main    
    with:
      registry: harbor.mongodb.dk
      run_number: ${{ github.run_number }}
      IMAGE_NAME: karsoekube/arm-base64
      PROJECT: base64
      REPOSITORY: github.com/jennermand/picluster.git
      branch: ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
    secrets:
      username: ${{ secrets.HARBOR_USERNAME  }}
      password: ${{ secrets.HARBOR_PASSWORD }}
      token: ${{ secrets.TOKEN }}
  
    # steps:
    #  runs-on: ubuntu-latest
    #   - name: Clone Repository
    #     run: |
    #       git clone <argocd-config-repo-url>
    #   - name: Install yq
    #     run: |
    #       sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
    #       sudo chmod a+x /usr/local/bin/yq
    #   - name: Update YAML File
    #     run: |
    #       yq -i '.spec.template.spec.containers[0].image = "harbor.example.com/chaturmail/chaturmail-backend:${{ github.run_number }}"' 'argocd-configs/chaturmail-pod.yaml'
  
    #   - name: Push to Repo
    #     run: |
    #       git config --global user.name "${{secrets.USERNAME_GITHUB}}"
    #       git config --global user.email "${{secrets.EMAIL_GITHUB}}"
    #       cd argocd-test-configs
    #       git add .
    #       git commit -m "Updated by GitHub Actions"
    #       git push <argocd-config-repo-url> --all
